### PR TITLE
Specify FILTER WHERE syntax not supported

### PR DESCRIPTION
**Pull request by michaelwheeler**
Subject: Redshift doesn't support FILTER WHERE syntax

### Feature or Bugfix
- Bugfix

### Purpose
- This PR just marks `supports_aggregate_filter_clause` as an unsupported database feature so that the ORM will fallback to CASE statements in conditional aggregation.

### Detail
- Details in the [Django docs for conditional aggregation](https://docs.djangoproject.com/en/2.1/ref/models/conditional-expressions/#conditional-aggregation).

### CODE REVIEW

**Comment by michaelwheeler** [comment]
Not in a huge hurry to fix the failing tests since Django 1.11 extended support will be ending in April, and I see in #50 that support is planned to be removed from this library as well. Please let me know if that is a problem.

**Comment by michaelwheeler** [comment]
Is it possible to rerun tests on this PR? I think it should be passing now that support for older Python and Django versions has been removed.

**Comment by shimizukawa** [comment]
@michaelwheeler can you rebase this PR on to origin/master? 
We have moved from travis to github actions at #72 Jan 4, 2021.

**Comment by michaelwheeler** [comment]
Replaced by #74 .

**Pull request closed without merging**
